name: CMake Tests
on:
  push:

jobs:
  buildTest:
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build
      run: ./install.sh ${{matrix.compiler}}

    - name: Test
      run: |
        cd ../build-class
        ctest

    - name: Results
      run: |
        cd ../build-class/Testing/Temporary
        cat LastTest.log